services:
  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    image: ghcr.io/tarefev/calorimeter-backend:latest
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
      - PORT=${BACKEND_PORT}
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
