services:
  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    image: ghcr.io/tarefev/calorimeter-backend:latest
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
      - PORT=${BACKEND_PORT}
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=calorimeter
      - POSTGRES_USER=calorimeter
      - POSTGRES_PASSWORD=calorimeter_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
